
# 配置文件说明
# https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/go_sdk/env_conf.html

title = "Client Config"

[Network]
#type rpc or channel
Type = "channel"
CAFile = "./cert/ca.crt"
Cert = "./cert/sdk.crt"
Key = "./cert/sdk.key"
[[Network.Connection]]
NodeURL = "127.0.0.1:20200"
GroupID = 1
# [[Network.Connection]]
# NodeURL="127.0.0.1:20200"
# GroupID=2

[Account]
# only support PEM format for now
KeyFile = "./accounts/0x83309d045a19c44dc3722d15a6abd472f95866ac.pem"

[Chain]
ChainID = 1
SMCrypto = false

[log]
Path = "./"
